### ISSUE TITLE
Proposal: Remove / Rename "Name" column in Dataset section

### ISSUE THREAD

**Issue by LudwigStumpp** [eugeneyan/open-llms#27]
At the moment, the first column in the [Dataset for finetuning](https://github.com/eugeneyan/open-llms#llm-datasets-for-fine-tuning) section is `Name` and includes the name of the corresponding model.

I find this very confusing as I would expect the first column to be the name of the dataset.

Therefore I would propose to either:
- Remove the current first column and content `Name` completely + instead move the `Dataset` column there.
- Rename the current first column to `Trained Model` and switch the positions with the `Dataset` column.

What do you think?

**Comment by eugeneyan** [comment]
I think it's useful to keep the model as a column as it's an example of how the dataset was used and the outcomes achieved (e.g., model evals).

I don't have a strong opinion on whether the first column should be dataset or model. Nonetheless, if I had to pick, I would lean towards the first column being the dataset as that's the main item being referenced (data instead of model).

**Comment by LudwigStumpp** [comment]
Alright! Thanks for your thoughts on this! Will leave it then for now as it is, as no strong opinions for now.
